export { createGoalAutoStartHandler } from "./auto-start"
export type { GoalAutoStartOptions, GoalContextEvent, GoalSessionInfo } from "./auto-start"
export { createGoalController, InvalidObjectiveError } from "./controller"
export type { GoalController } from "./controller"
export { registerConfiguredGoalFeature } from "./configured-register"
export type { ConfiguredGoalContext, RegisterConfiguredGoalFeatureOptions } from "./configured-register"
export { buildContinuationPrompt } from "./prompt"
export { registerGoalFeature, registerGoalFeatureEffect } from "./register"
export type { GoalFeatureContext, RegisteredGoalFeature, RegisterGoalFeatureOptions } from "./register"
export { createGoalRuntime } from "./runtime"
export type { GoalEvent, GoalRuntime, GoalRuntimeDependencies } from "./runtime"
export { goalFilePath } from "./store"
export { createGoalTools } from "./tools"
export type { GoalToolDefinition, GoalToolExecutionContext, GoalToolsDependencies } from "./tools"
export { GOAL_STATUS_VALUES, GoalSchema, GoalStatusSchema } from "./types"
export type { Goal, GoalStatus, GoalTrace } from "./types"
