export { AGENT_NAMES, MODE_NAMES, agentID, agentName, explicitMode, modeMarker } from "./catalog"
export type { AgentName, ModeName } from "./catalog"
export { renderAgent, renderMode, bindNative } from "./render"
export type { PromptContext } from "./render"
export { resolveVariant } from "../omo/modes/src/variant-resolver"
